#ifndef __YT_AUTH_ERRORCODE_H__
#define __YT_AUTH_ERRORCODE_H__

#define YT_AUTH_ERROR_FETCH_FAIL            (1002)
#define YT_AUTH_ERROR_DECODE_FAIL           (3004)
#define YT_AUTH_ERROR_EMPTY_STRING          (3005)
#define YT_AUTH_ERROR_UNMATCH_DEVICE_INFO   (3013)
#define YT_AUTH_ERROR_UNMATCH_IDENTIFIER    (3015)
#define YT_AUTH_ERROR_EMPTY_IDENTIFIER      (3016)
#define YT_AUTH_ERROR_TIME_EXPIRED          (3018)
#define YT_AUTH_ERROR_UNMATCH_SECRET_KEY    (3024)
#define YT_AUTH_ERROR_INVALID_DEVICE_INFO   (4003)
#define YT_AUTH_ERROR_FUNC_NOT_IMPLEMENT    (5001)

#endif // __YT_AUTH_ERRORCODE_H__